name: NCTL Scan Dockerfile Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

env:
  NIRMATA_API_KEY: ${{secrets.NIRMATA_API_KEY}}


jobs:
  NCTL-Scan-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out main repository code
        uses: actions/checkout@v4

      - name: Download and Install nctl
        shell: bash
        run: |
          #!/bin/bash

          shopt -s expand_aliases

          if [ -z "$NO_COLOR" ]; then
            alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
            alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
          else
            alias log_info="echo \"INFO:\""
            alias log_error="echo \"ERROR:\""
          fi

          set -e

          # Determine the download URL based on the release version
          download_url="https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_0.1-publish-report/nctl_0.1-publish-report_linux_64-bit.zip"

          log_info "Downloading nctl version 0.1-publish-report from ${download_url}"
          curl -L -o nctl.zip $download_url

          log_info "Unzipping nctl..."
          unzip -q nctl.zip

          log_info "Making nctl executable..."
          chmod +x nctl

      - name: NCTL Scan - Dockerfile
        run: ./nctl analyze git-repo --policies ./policy/ --publish --publish-url https://devtest2.nirmata.co/policies/api/policyReportResult
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
